DROP TABLE IF EXISTS widget;
CREATE TABLE widget (
  id SERIAL PRIMARY KEY,
  name VARCHAR,
  unit_price NUMERIC(10,2)
);

DROP TABLE IF EXISTS gadget;
CREATE TABLE gadget (
  id SERIAL PRIMARY KEY,
  name VARCHAR,
  price VARCHAR
);
